version: '3'

services:
  auth-app:
    container_name: 'AuthService-Lebedev'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '28081:8081'
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
