apiVersion: apps/v1
kind: Deployment
metadata:
  name: lebedev-auth-deployment
  labels:
    app: lebedev-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lebedev-auth
  template:
    metadata:
      labels:
        app: lebedev-auth
    spec:
      containers:
      - name: lebedev-auth-container
        image: kotbegemott/auth-service:2
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 5
        volumeMounts:
        - name: photos
          mountPath: /usr/photos
        env:
        # Database (secret)
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_name

        # Database (public)
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_port
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_schema

        # Kafka
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-auth-configmap
              key: kafka_host
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-auth-configmap
              key: kafka_port
        - name: KAFKA_PRODUCER_TOPIC
          valueFrom:
            configMapKeyRef:
              name: lebedev-auth-configmap
              key: kafka_producer_topic
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: lebedev-faces-pvc
