apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lebedev-faces-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: yc-network-hdd
